cse/urls.py
from django.urls import path,re_path
from cse import views as user_view
from django.conf import  settings
from django.contrib.auth import views as auth_views


app_name = 'cse'

urlpatterns = [

    path('test/',user_view.testing,name='test'),
    path('profile/',user_view.profile,name='profile'),
    path('profile_medi/',user_view.profile_medi,name='profile_medi'),
    path('per_medi_info/',user_view.per_medi_info,name='per_medi_info'),



    path('', user_view.staring, name='staring'),
    path('login/', user_view.login, name='login'),
    path('logout/', user_view.logout, name='logout'),
    path('register/', user_view.register, name='register'),

    path('password_reset/', user_view.password_reset, name='password_reset'),
    path('password_reset/done/', user_view.password_reset_done, name='password_reset_done'),
    path('password_reset/complete/', user_view.password_reset_complete, name='password_reset_complete'),


    path('index/', user_view.index, name='index'),
    path('contact/', user_view.contact, name='contact'),
    path('feedback/', user_view.feedback, name='feedback'),

    path('doctors/', user_view.doctors, name='doctors'),
    path('patient_to_doctor/', user_view.patient_to_doctor, name='patient_to_doctor'),
    path('<int:doctor_id>/doctors_delete/', user_view.doctors_delete, name='doctors_delete'),
    path('<int:doctor_id>/full_doctor/', user_view.full_doctor, name='full_doctor'),

    path('services/', user_view.services, name='services'),
    path('about_us/', user_view.about_us, name='about_us'),


    path('patientconfirm/', user_view.patientconfirm, name='patientconfirm'),
    path('pregform/', user_view.pregform, name='pregform'),
    # path('patientreg/',user_view.patient_reg,name='patient_reg'),
    # path('pdf/',user_view.GeneratePDF.as_view(),name='pdf'),
    path('pdf/',user_view.pdf,name='pdf'),


    path('newdoctor/', user_view.newdoctor, name='newdoctor'),
    path('newdoctor_reg/', user_view.newdoctorreg, name='newdoctor_reg'),



    # MedicineInfo
    path('medicineinfo/',user_view.medicineinfo,name='medicineinfo'),
    path('medisearch/',user_view.medisearch,name='medisearch'),
    path('medisearch2/',user_view.medisearch2,name='medisearch2'),
    path('newmedicine/',user_view.newmedicine,name='newmedicine'),
    path('mediregister/',user_view.mediregister,name='mediregister'),
    path('medi_pre/',user_view.medi_pre,name='medi_pre'),
    path('medichange/',user_view.medichange,name='medichange'),
    path('mediadd/',user_view.mediadd,name='mediadd'),

    # re_path(r'^medicineinfo/(?P<filter_by>[a-zA_Z]+)/$', user_view.medicineinfo,name='medicineinfo'),
    # re_path(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),


    # account confirmations
    # path('activate/<uid>/<token>/', views.activate,name='activate'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', user_view.activate, name='activate'),

    re_path(r'^passactivate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', user_view.passactivate, name='passactivate'),

]

medical/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cse.urls')),

    path('accounts/', include('allauth.urls')),  # new
    path('cse/',include('cse.urls',namespace='lol')),
]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cse/views.py
import  json
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.models import User,AbstractUser
from django.contrib.auth import logout as auth_logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404,redirect,HttpResponse,NoReverseMatch,HttpResponsePermanentRedirect,Http404,HttpResponseRedirect
from django.db.models import Q
from .token import account_activation_token
from .token_admin import account_activation_token_admin
from django.utils.encoding import force_bytes,force_text
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.sites.models import Site
from django.template.loader import render_to_string
from django.conf import  settings
from django.core.mail import send_mail,EmailMessage
from django.contrib import  messages
from django.shortcuts import render
from datetime import date,datetime
from .models import CustomUser,Doctors,FeebBack,MedicalInfo,MedicineInfo
from django.contrib import messages
from  django.http import HttpResponse
from django.views.generic import View
from django.template.loader import get_template
from cse.utils import render_to_pdf
from django.shortcuts import get_object_or_404

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']



# ----------------- Testing ----------------------------

def testing(request):

    return render(request, 'cse/test3.html')
# ---------------------- Medical Info --------------------

def calculate_age(born):
    today = date.today()
    try:
        birthday = born.replace(year=today.year)
    except ValueError: # raised when birth date is February 29 and the current year is not a leap year
        birthday = born.replace(year=today.year, month=born.month+1, day=1)
    if birthday > today:
        return today.year - born.year - 1
    else:
        return today.year - born.year


def per_medi_info(request):
    if not request.user.is_authenticated:
        last_ten = FeebBack.objects.all().order_by('-id')[:10]
        return render(request, 'cse/staring.html', {'messages': last_ten})
    else:
        if request.method == 'POST':
            t_patient = request.user
            t_doctor = Doctors.objects.get(doctor_id=request.POST.get('in_doc_id'))
            medi_in = MedicalInfo.objects.get(id=request.POST.get('in_mediingo_id'))
            context = {
                'tpatient': t_patient,
                'tdoctor': t_doctor,

                'thistory': medi_in.history,
                'tadditional_field': medi_in.add_info,
                'ttestadvised': medi_in.test_advise,

                'today_date': date.today(),
                'agee': medi_in.age,

                '1_medi_name': medi_in.medi_name_1,
                '1_drug_limit': medi_in.drug_limit_1,
                '1_days': medi_in.num_of_day_1,
                '1_eat': medi_in.eat_time_1,

                '2_medi_name': medi_in.medi_name_2,
                '2_drug_limit': medi_in.drug_limit_2,
                '2_days': medi_in.num_of_day_2,
                '2_eat': medi_in.eat_time_2,

                '3_medi_name': medi_in.medi_name_3,
                '3_drug_limit': medi_in.drug_limit_3,
                '3_days': medi_in.num_of_day_3,
                '3_eat': medi_in.eat_time_3,

                '4_medi_name': medi_in.medi_name_4,
                '4_drug_limit': medi_in.drug_limit_4,
                '4_days': medi_in.num_of_day_4,
                '4_eat': medi_in.eat_time_4,

                '5_medi_name': medi_in.medi_name_5,
                '5_drug_limit': medi_in.drug_limit_5,
                '5_days': medi_in.num_of_day_5,
                '5_eat': medi_in.eat_time_5,

                '6_medi_name': medi_in.medi_name_6,
                '6_drug_limit': medi_in.drug_limit_6,
                '6_days': medi_in.num_of_day_6,
                '6_eat': medi_in.eat_time_6,

                '7_medi_name': medi_in.medi_name_7,
                '7_drug_limit':medi_in.drug_limit_7,
                '7_days':medi_in.num_of_day_7,
                '7_eat': medi_in.eat_time_7,

                '8_medi_name': medi_in.medi_name_8,
                '8_drug_limit': medi_in.drug_limit_8,
                '8_days': medi_in.num_of_day_8,
                '8_eat': medi_in.eat_time_8,

                '9_medi_name': medi_in.medi_name_9,
                '9_drug_limit': medi_in.drug_limit_9,
                '9_days': medi_in.num_of_day_9,
                '9_eat': medi_in.eat_time_9,

                '10_medi_name': medi_in.medi_name_10,
                '10_drug_limit': medi_in.drug_limit_10,
                '10_days': medi_in.num_of_day_10,
                '10_eat': medi_in.eat_time_10
            }
            # html = template.render(context)
            # return HttpResponse(html)
            pdf = render_to_pdf('cse/prescription.html', context)

            # c = MedicalInfo(user_id=t_patient.id, prescription=pdf)
            # c.save()
            if pdf:
                response = HttpResponse(pdf, content_type='application/pdf')
                filename = "Patient_%s.pdf" % ("Prescription")
                content = "inline; filename='%s'" % (filename)
                download = request.GET.get("download")
                if download:
                    content = "attachment; filename='%s'" % (filename)
                response['Content-Disposition'] = content
                return response
            else:
                return HttpResponse("Not found")

        else:
            userinfo = request.user
            medical = MedicalInfo.objects.filter(user_id=request.user.id)
            return render(request, 'cse/profile.html', {'userinfo': userinfo, 'medical': medical})


# ----------------------Login or Register with Logout--------------------

def logout(request):
    auth_logout(request)
    last_ten = FeebBack.objects.all().order_by('-id')[:10]
    return render(request, 'cse/staring.html', {'messages': last_ten})

def login(request):
        if request.method == 'POST':
                # temail = request.POST['useremail']
                # tpassword = request.POST['password']
                temail = request.POST.get('useremail')
                tpassword = request.POST.get('password')
                user = authenticate(email=temail, password=tpassword)
                if user is not None:
                        if user.is_active:
                                auth_login(request, user)
                                if request.user.is_superuser or user.user_type == 'Admin':
                                    last_ten = FeebBack.objects.all().order_by('-id')[:10]
                                    return render(request, 'cse/index_admin.html', {'messages': last_ten})
                                else:
                                    last_ten = FeebBack.objects.all().order_by('-id')[:10]
                                    return render(request, 'cse/index.html',{'messages': last_ten})

                        else:
                                messages.error(request, 'Your account has been disabled..!')
                                return render(request, 'cse/login.html')
                else:
                        messages.error(request, 'Invalid login..!')
                        return render(request, 'cse/login.html')
        else:
            return render(request, 'cse/login.html')


def register(request):
        if request.method=='POST':
                tfirstname = request.POST.get('firstname')
                tlastname = request.POST.get('lastname')
                tusername = request.POST.get('username')
                tbdate = request.POST.get('date_of_birth')
                tgender = request.POST.get('gender')
                taddress = request.POST.get('address')
                tmobileno = request.POST.get('mobileno')
                ttelno = request.POST.get('telno')
                tuseremail = request.POST.get('useremail')
                tusertype = request.POST.get('usertype')
                tregno = request.POST.get('regno')
                tdepartment = request.POST.get('department')
                tposition = request.POST.get('position')
                tbloodgroup = request.POST.get('bloodgroup')
                theight = request.POST.get('height')
                tpassword = request.POST.get('psw')
                tnowdate = datetime.today()
                tpas_reset = 0

                c = CustomUser(first_name=tfirstname,last_name=tlastname,username=tusername,date_of_birth=tbdate,gender=tgender,address=taddress,
                               mobile_no=tmobileno,tel_no=ttelno,email=tuseremail,user_type=tusertype,reg_no=tregno,department=tdepartment,
                               designation=tposition,blood_group=tbloodgroup,height=theight,is_superuser=False,date_joined=tnowdate,
                               is_staff=False,last_login=None,pass_reset=tpas_reset)


                c.set_password(tpassword)
                c.photos = request.FILES['userphotos']
                file_type = c.photos.url.split('.')[-1]
                file_type = file_type.lower()
                if file_type not in IMAGE_FILE_TYPES:
                        messages.error(request, 'Image file must be PNG, JPG, or JPEG')
                        return render(request, 'cse/register.html')

                if CustomUser.objects.filter(username=request.POST.get('username')).exists():
                        messages.error(request, 'User name is already exists..!')
                        return render(request, 'cse/register.html')

                if CustomUser.objects.filter(email=request.POST.get('useremail')).exists():
                        messages.error(request, 'User email is already exists..!')
                        return render(request, 'cse/register.html')

                c.is_active=False
                c.save()

                if c.user_type == 'Admin':

cse/templates/cse/confirm_email.html
{% autoescape off %}
    Hi {{ user.username }},
    Thanks for your registration in SUST Medical Center.
    Please click on the link below to confirm your registration,

    http://{{ domain }}{% url 'cse:activate' uidb64=uid token=token %}

    If you didn't request  to open  account in SUST Medical Center, you can safely  ignore this email.

    Sincerely,
    SUST Medical Center Team

{% endautoescape %}

cse/templates/cse/feed2.html
{% autoescape off %}
    Dear {{ user.username }},
    Thanks for contacting our doctor! Resolving your issues and problems are our top priority..

    Your request has been received and Our doctor'll get back to you within 24 hours.
    If you’d like to add additional comments, please reply to this email.

    Feel free to take a look at our Help Center as we may already have an answer for you there.
    Thanks and have a great day!

    Sincerely,
    SUST Medical Center Team

{% endautoescape %}

cse/templates/cse/prescription.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Patient Prescription</title>
            {% load staticfiles %}
        <style type="text/css">
            .a{
                padding-left: -0px;
                text-align: left;
                font-size: 35px;
                color: green;
            }
            .c{
                padding-left: -65px;
                padding-right: -50px;
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .ad{
                padding-left: -50px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .e{
                padding-left: -90px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .f{
                padding-left: -52px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .g{
                padding-left: -64px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }






            .b{
                font-size: 20px;
                color: green;
                {#padding-top: 0px;#}
                padding-left: -40px;
                padding-right: -25px;
                text-align: right;
            }
            .d{
                font-size: 12px;
                color: black;
                padding-right: 0px;
                text-align: right;
            }





            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }




            .i{
                position: static;
                padding-left: 10px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .j{
                position: static;
                padding-left: 35px;
                {#padding-right: -50px;#}
                text-align: center;
                font-size: 14px;
                color: black;
            }
            .k{
                position: static;
                font-size: 12px;
                color: black;
                padding-right: 60px;
                text-align: right;
            }


            .l{
                padding-left: -282px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .m{
                padding-left: -230px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }
            .n{
                padding-left: -255px;
                {#padding-right: -50px;#}
                text-align: left;
                font-size: 14px;
                color: black;
            }


            #customers {
                  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
                  border-collapse: collapse;
                  width: 100%;
                    font-size: 12px;
                text-align: left;
                table-layout: fixed;
                font-size: 12px;

            }

            #customers td, #customers th {
                padding: 2px;
                border: 1px solid black;


            }
            #customers th {
                  padding-top: 12px;
                  padding-bottom: 12px;
                  text-align: center;
                  background-color: #4CAF50;
                  color: black;
                font-size: 10px;

            }





            #customerss {
                  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
                  border-collapse: collapse;
                  width: 100%;
                    font-size: 12px;
                text-align: left;
                table-layout: fixed;

            }

            #customerss td, #customerss th {
                padding: 2px;
                border: 1px solid black;
                font-size: 12px;


            }
            #customerss th {
                  padding-top: 6px;
                  padding-bottom: 6px;
                  text-align: center;
                  background-color: #4CAF50;
                  color: black;
                font-size: 10px;
            }
            .rx{
                font-size: 22px;
                color: black;
            }
            .sing{
                text-align: right;
                font-size: 18px;
            }



        </style>
    </head>
    <bodyz>
        <div>
            <table>
                <tr>
                    <th class="a">SUST Medical Center</th>
                    <th class="b">Dr. {{ tdoctor.first_name }} {{ tdoctor.last_name }}</th>
                </tr>
                <tr>
                    <th class="c">Shahjalal University of Science and Technology</th>
                    <th class="d">{{ tdoctor.qualification }}</th>
                </tr>
                <tr>
                    <th class="ad">Address: University Ave, Sylhet 3114</th>
                    <th class="d">{{ tdoctor.positions }}</th>
                </tr>

                <tr>
                    <th class="e">Phone: + 880-821-713491</th>
                    <th class="d">Phone: {{ tdoctor.mobile_no}}</th>
                </tr>
                <tr>
                    <th class="f">Email: bijoysust.system@gmail.com</th>
                    <th class="d">Tel No: {{ tdoctor.tel_no}}</th>
                </tr>
                <tr>
                    <th class="g">Website: sustmedicalcenter.com</th>
                    <th class="d">Email: {{ tdoctor.email}}</th>
                </tr>
            </table>
        </div>
        <hr class='hrItem' />
{#        <div>#}
{#            <br>#}
{#        </div>#}
        <div>
            <table>
                <tr>
                    <th class="i">Name: {{ tpatient.first_name }} {{ tpatient.last_name }}</th>
                    <th class="j">Age: {{ agee}} Years</th>
                    <th class="k">Date: {{ today_date }}</th>
                </tr>
            </table>
        </div>
        <div>
            <br>
        </div>
        <table id="customers">
             <tr>
                <th>History</th>
                <th>Additional Information</th>
                <th>Tests Advised</th>
             </tr>
             <tr>
                 <td>{{ thistory }}</td>
                 <td>{{ tadditional_field }}</td>
                 <td>{{ ttestadvised }}</td>
             </tr>
        </table>
{#        <div>#}
{#            <br>#}
{#        </div>#}
        <div>
            <p class="rx">Rx</p>
        </div>
                <table id="customerss">
             <tr>
                <th>Medicine Name</th>
                <th>Eating Time</th>
                <th>Drug Limit</th>
                <th>Number of Days</th>
             </tr>
             <tr>
                 <td>{{ 1_medi_name }}</td>
                 <td>{{ 1_eat }}</td>
                 <td>{{ 1_drug_limit }}</td>
                 <td>{{ 1_days }}</td>
             </tr>
             <tr>
                 <td>{{ 2_medi_name }}</td>
                 <td>{{ 2_eat }}</td>
                 <td>{{ 2_drug_limit }}</td>
                 <td>{{ 2_days }}</td>
             </tr>
             <tr>
                 <td>{{ 3_medi_name }}</td>
                 <td>{{ 3_eat }}</td>
                 <td>{{ 3_drug_limit }}</td>
                 <td>{{ 3_days }}</td>
             </tr>
             <tr>
                 <td>{{ 4_medi_name }}</td>
                 <td>{{ 4_eat }}</td>
                 <td>{{ 4_drug_limit }}</td>
                 <td>{{ 4_days }}</td>
             </tr>
             <tr>
                 <td>{{ 5_medi_name }}</td>
                 <td>{{ 5_eat }}</td>
                 <td>{{ 5_drug_limit }}</td>
                 <td>{{ 5_days }}</td>
             </tr>
             <tr>
                 <td>{{ 6_medi_name }}</td>
                 <td>{{ 6_eat }}</td>
                 <td>{{ 6_drug_limit }}</td>
                 <td>{{ 6_days }}</td>
             </tr>
             <tr>
                 <td>{{ 7_medi_name }}</td>
                 <td>{{ 7_eat }}</td>
                 <td>{{ 7_drug_limit }}</td>
                 <td>{{ 7_days }}</td>
             </tr>
             <tr>
                 <td>{{ 8_medi_name }}</td>
                 <td>{{ 8_eat }}</td>
                 <td>{{ 8_drug_limit }}</td>
                 <td>{{ 8_days }}</td>
             </tr>
             <tr>
                 <td>{{ 9_medi_name }}</td>
                 <td>{{ 9_eat }}</td>
                 <td>{{ 9_drug_limit }}</td>
                 <td>{{ 9_days }}</td>
             </tr>
             <tr>
                 <td>{{ 10_medi_name }}</td>
                 <td>{{ 10_eat }}</td>
                 <td>{{ 10_drug_limit }}</td>
                 <td>{{ 10_days }}</td>
             </tr>

        </table>
        <div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>

        </div>
        <div>
            <p class="sing">Doctor's Signature</p>
        </div>
{#        <div>#}
{#            <br>#}
{#        </div>#}
{#        <div>#}
{#        <div>#}
{#            <table>#}
{#                <tr>#}
{#                    <td class="medi_1">Medicine Name</td>#}
{#                    <td class="medi_2">Eating Time</td>#}
{#                    <td class="medi_3">Drug Limit</td>#}
{#                    <td class="medi_4">Number of Days</td>#}
{##}
{#                </tr>#}
{#            </table>#}
{#        </div>#}
{#        <div>#}
{#            <table class="table">#}
{#                <tr>#}
{#                    <th class="l"><u>History:</u></th>#}
{#                </tr>#}
{#                <tr>#}
{#                    <th class="l"> {{ thistory }}</th>#}
{#                </tr>#}
{#                <tr>#}
{#                    <th class="m"><u>Additional Information:</u></th>#}
{#                </tr>#}
{#                <tr>#}
{#                    <th class="m">{{ tadditional_field }}</th>#}
{#                </tr>#}
{#                <tr>#}
{#                    <th class="n"><u>Tests Advised:</u></th>#}
{#                </tr>#}
{#                <tr>#}
{#                    <th class="n">{{ ttestadvised }}</th>#}
{#                </tr>#}
{#            </table>#}
{#        </div>#}

    </bodyz>
</html>